name: Dev Enhancement
description: Propose a build, tooling, or developer workflow improvement
labels: ["dev"]

body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What tooling, build, or workflow change are you proposing?
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: What problem does this solve or what does it improve for development?
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Notes
      description: Any specific tools, plugins, or configuration details to consider?
    validations:
      required: false
